# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Fingerprint
version:      0.15
version_from: lib/Email/Fingerprint.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Std:                    0
    Fcntl:                         0
    File::Slurp:                   0
    FileHandle:                    0
    List::MoreUtils:               0
    Mail::Header:                  0
    NDBM_File:                     0
    overload:                      0
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
