--- #YAML:1.0
name:               Email-Fingerprint
version:            0.41
abstract:           Calculate a digest for recognizing duplicate emails
author:
  - Len Budney <lbudney@pobox.com>
license:            perl
distribution_type:  module
installdirs:  site
configure_requires:
  ExtUtils::MakeMaker:          '>= 6.31'
build_requires:
  ExtUtils::MakeMaker:          '>= 6.31'
  File::Slurp:                  0.01
  Test::Exception:              0.07
  Test::More:                   0
  Test::Warn:                   0.09
  Test::Stdout:                 0
requires:
  Carp:                         0
  Class::Std:                   0.0.2
  Fcntl:                        0
  File::Path:			        2.08
  File::Spec:                   0.82
  FileHandle:                   0
  List::MoreUtils:              0.04
  LockFile::Simple:             0.2.0
  Mail::Header:                 1.40
  AnyDBM_File:                  0
  overload:                     0
  Scalar::Util:                 0
no_index:
    directory:
        - t
        - inc
generated_by: Hand
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
