name:         Email-Fingerprint
version:      0.31
author:
  - Len Budney <lbudney@pobox.com>
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
installdirs:  site
configure_requires:
  ExtUtils::MakeMaker:          '>= 6.31'
requires:
  Carp:                         0
  Class::Std:                   0
  English:                      0
  Fcntl:                        0
  File::Path:			        0
  File::Slurp:                  0
  File::Spec:                   0
  FileHandle:                   0
  List::MoreUtils:              0
  Mail::Header:                 0
  NDBM_File:                    0
  Scalar::Util:                 0
  Test::Differences:            0
  Test::Exception:              0
  Test::More:                   0
  Test::Warn:                   0
  overload:                     0
  version:                      0
build_requires:
  English:                      0
  Data::Dump:                   0
  File::Path:			        0
  File::Slurp:                  0
  File::Spec:                   0
  Test::Differences:            0
  Test::Exception:              0
  Test::More:                   0
  Test::Stdout:                 0
  Test::Warn:                   0
  lib:                          0
  overload:                     0
  version:                      0
distribution_type: module
license: perl
generated_by: Hand
