name:         Email-Fingerprint
version:      0.20
author:
  - Len Budney <lbudney@pobox.com>
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
installdirs:  site
requires:
  Carp:                         0
  Test::More:                   0
  Fcntl:                        0
  FileHandle:                   0
  Mail::Header:                 0
  NDBM_File:                    0
  Class::Std:                   0
  Scalar::Util:                 0
  overload:                     0
  File::Slurp:                  0
  List::MoreUtils:              0
build_requires:
  ExtUtils::MakeMaker           >= 6.31
  Test::More                    0
  Test::Exception               0
  Test::Warn                    0
  Test::Stdout                  0
  File::Spec                    0
  File::Slurp                   0
  English                       0
distribution_type: module
license: perl
generated_by: Hand
